### PR TITLE
Re-add support for Ruby 1.9.3

### LINKED ISSUE #13: v1.3.1 requires Ruby >= 2.0, breaks Jekyll install on at least ubuntu 14.04
If you're going to require ruby 2.0, then you should increment your major version number as well. It's a backwards compatibility breaking change, especially since Jekyll depends on jekyll-gist ~> 1.0

### PR DESCRIPTION
**Pull request by parkr**
Fixes #13, follow-up to #11.

We need a fix for https://github.com/jekyll/jekyll-gist/pull/7#issuecomment-128341980 that works in Ruby 1.9.3.

/cc @gr4y

### CODE REVIEW

**Comment by gr4y** [comment]
I will take a look at that when my Mac finsihed compiling ruby 1.9.3, which might take some more minutes. But I just asked my self if the issue #7 will be un-fixed by fixing #13. 

`Net::OpenTimeout` is not available in Ruby 1.9.3 which indicates that the timeout which fixed #7 won't be available either in `net/http` in 1.9.3.

**Comment by gr4y** [comment]
`net/http` in Ruby 1.9.3 throws an `TimeoutError` [when it times out](http://ruby-doc.org/stdlib-1.9.3/libdoc/net/http/rdoc/Net/HTTP.html#open_timeout). In Ruby 2.0 `net/http` throws an special `Exception` for each timeout. 

So by just removing the ReadTimeout and OpenTimeout from the code I ran into `undefined method `empty?' for #<URI::HTTPS:0x007fd203cd4240>`

So I tried wrapping the begin..rescue..end block into another begin..rescue..end block and catching NameError, which worked out, but results in missing `noscript` and failing specs even when the network connection is working fine.

**Comment by gr4y** [comment]
So what's your plan on this? I seriously don't know what to do except removing the feature introduced in #7 or reverting the commits made in #11 to fix that.

**Comment by parkr** [comment]
> So I tried wrapping the begin..rescue..end block into another begin..rescue..end block and catching NameError

Lol a NameError is usually not something you want to catch... If `empty?` doesn't exist somewhere, then some code is borked and we need to figure out where it went wrong there.

I think I fixed it by just spiking those error classes out.

**Comment by gr4y** [comment]
@parkr I guessed that catching NameError won't be a smart idea. By the way: I haven't heard the term "spiking out" ever before. Seems I am a little out of the loop when it comes to ruby. Sorry about that. :sob:

**Comment by parkr** [comment]
> By the way: I haven't heard the term "spiking out" ever before. Seems I am a little out of the loop when it comes to ruby. Sorry about that.

It's absolutely no problem! "Spike out" is an idiom. When I say "Spike out code", I mean "write the initial version". A working scaffold. Sorry for that! I should be more considerate of people who don't speak idiomatic English.

**Comment by gr4y** [comment]
It's a rather cool way to fix backwards compatibility problems like that one, so I learned something new here. :smile:
