### PR TITLE
rename Liquid 4 has_key to key to add compatibility for liquid 4

### PR DESCRIPTION
**Pull request by marcanuy**
Using Liquid 4 `key`.

### CODE REVIEW

**Comment by benbalter** [comment]
Based on the failing tests, we may need to see if context responds to `key?` and if not use `has_key?` to maintain compatibility with pre 3.5.

**Comment by marcanuy** [comment]
What about this? Having each code for both versions:

``` ruby

          if Gem.loaded_specs['liquid'].version < Gem::Version.create('4.0')
            if context.has_key?(gist_id)
              gist_id = context[gist_id]
            end
            if context.has_key?(filename)
              filename = context[filename]
            end
          else
            if context.key?(gist_id)
              gist_id = context[gist_id]
            end
            if context.key?(filename)
              filename = context[filename]
            end
          end

```
Until there is another more elegant solution.

**Comment by parkr** [comment]
What about a helper method?

```ruby
          
            if context_contains_key?(context, gist_id)
              gist_id = context[gist_id]
            end

            if context_contains_key?(context, filename)
              filename = context[filename]
            end
      
# ...

def context_contains_key?(context, key)
  if context.respond_to?(:has_key?)
    context.has_key?(key)
  else
    context.key?(key)
  end
end
```

**Comment by DirtyF** [comment]
@benbalter you're right without a helper it is not backward compatible

>   Liquid Exception: undefined method `key?' for #<Liquid::Context:0x007fe5abf97cf0> in /Users/frank/code/jamstatic.fr/_posts/2016-09-18-utiliser-des-plugins-jekyll-avec-github-pages.md
jekyll 3.4.3 | Error:  undefined method `key?' for #<Liquid::Context:0x007fe5abf97cf0>

**Comment by DirtyF** [comment]
Works fine on 3.4.3 and 3.5, shouldn't we remove the tests on Ruby 1.9?

**Comment by parkr** [comment]
> Do this plugin still want to support Jekyll 2.0?

Jekyll 2.0 is old enough that I would say no, we don't need support for it.

**Comment by parkr** [comment]
@jekyllbot: merge
